name: Test Python and Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint `ls -R | grep .py | xargs`
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag telegram-bot-image:$(date + %s)

